
import React, { useState } from 'react';
import { generateMenuSuggestion } from '../services/geminiService.ts';

const QuotationWizard: React.FC = () => {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    eventType: 'Corporate Meeting',
    guestCount: 20,
    preferences: ''
  });
  const [loading, setLoading] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<any>(null);

  const handleSuggest = async () => {
    setLoading(true);
    const suggestion = await generateMenuSuggestion(formData.eventType, formData.guestCount, formData.preferences);
    setAiSuggestion(suggestion);
    setLoading(false);
    setStep(2);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <div className="bg-white rounded-[2.5rem] shadow-2xl p-8 md:p-12 border border-blue-50">
        {step === 1 ? (
          <div className="space-y-8">
            <div className="text-center">
              <span className="bg-blue-50 text-blue-900 px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-4 inline-block">Smart Assistant</span>
              <h1 className="text-4xl font-serif font-bold text-blue-950 mb-4">Plan Your Celebration</h1>
              <p className="text-slate-600">Our AI assistant will help you curate the perfect menu for your event.</p>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <label className="block text-sm font-semibold text-slate-700">Event Type</label>
                <select 
                  className="w-full px-5 py-4 rounded-xl border border-slate-200 bg-slate-50 outline-none focus:border-blue-600"
                  value={formData.eventType}
                  onChange={e => setFormData({...formData, eventType: e.target.value})}
                >
                  <option>Corporate Meeting</option>
                  <option>Birthday Party</option>
                  <option>Wedding Ceremony</option>
                  <option>High Tea Gathering</option>
                  <option>Traditional Function</option>
                </select>
              </div>
              <div className="space-y-4">
                <label className="block text-sm font-semibold text-slate-700">Approx. Guests</label>
                <input 
                  type="number" 
                  className="w-full px-5 py-4 rounded-xl border border-slate-200 bg-slate-50 outline-none focus:border-blue-600"
                  value={formData.guestCount}
                  onChange={e => setFormData({...formData, guestCount: parseInt(e.target.value)})}
                />
              </div>
            </div>

            <div className="space-y-4">
              <label className="block text-sm font-semibold text-slate-700">Specific Requirements or Taste Preferences</label>
              <textarea 
                placeholder="e.g., Spicy savories, kid-friendly options, or low-sugar desserts..."
                className="w-full px-5 py-4 rounded-xl border border-slate-200 bg-slate-50 outline-none focus:border-blue-600 min-h-[120px]"
                value={formData.preferences}
                onChange={e => setFormData({...formData, preferences: e.target.value})}
              />
            </div>

            <button 
              onClick={handleSuggest}
              disabled={loading}
              className="w-full bg-blue-900 text-white py-5 rounded-2xl font-bold text-lg hover:bg-blue-800 transition-all flex justify-center items-center gap-3 shadow-xl shadow-blue-900/20"
            >
              {loading ? (
                <>
                  <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Curating Your Menu...
                </>
              ) : (
                'Generate Personalized Suggestion'
              )}
            </button>
          </div>
        ) : (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex justify-between items-center mb-6">
              <button 
                onClick={() => setStep(1)}
                className="text-blue-900 font-semibold flex items-center gap-2 hover:opacity-70"
              >
                ← Back to Edit
              </button>
              <span className="text-slate-400 text-sm">Suggestion generated by Droselle AI</span>
            </div>

            {aiSuggestion && (
              <div className="space-y-10">
                <div className="text-center">
                  <h2 className="text-3xl font-serif font-bold text-blue-950 mb-4">Your Custom Celebration Menu</h2>
                  <p className="text-slate-600 leading-relaxed italic">"{aiSuggestion.introduction}"</p>
                </div>

                <div className="grid sm:grid-cols-2 gap-6">
                  {aiSuggestion.menuItems.map((item: any, i: number) => (
                    <div key={i} className="p-6 bg-blue-50/30 rounded-2xl border border-blue-50 hover:border-blue-200 transition-colors">
                      <span className="text-[10px] font-bold uppercase tracking-widest text-blue-700 mb-2 block">{item.category}</span>
                      <h4 className="font-bold text-blue-900 text-lg mb-2">{item.name}</h4>
                      <p className="text-sm text-slate-600 leading-relaxed">{item.description}</p>
                    </div>
                  ))}
                </div>

                <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100">
                  <p className="text-blue-900 text-sm font-medium text-center">
                    {aiSuggestion.closingNote}
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-4 pt-6 border-t border-slate-100">
                  <button 
                    onClick={() => alert('Quotation request sent! Our team will contact you soon.')}
                    className="flex-1 bg-blue-900 text-white py-4 rounded-xl font-bold hover:bg-blue-800 transition-all shadow-lg shadow-blue-900/10"
                  >
                    Request Official Quotation
                  </button>
                  <button 
                    onClick={() => window.print()}
                    className="flex-1 bg-white text-slate-600 border border-slate-200 py-4 rounded-xl font-bold hover:bg-slate-50 transition-all"
                  >
                    Download Menu PDF
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default QuotationWizard;
